### ISSUE TITLE
MIP1 官方组件整体迁移至 MIP2

### ISSUE THREAD

**Issue by huanghuiquan** [mipengine/mip2-extensions#415]
## 背景

由于 MIP 核心已经全量升级到 MIP2，为了保持 MIP1 和 MIP2 官方组件的统一，让站长能使用最新的 MIP2 组件，急需将 MIP1 的官方组件迁移至 mip2-extensions respo 下，为后续的组件升级做好铺垫。

## 需要迁移的组件

- [x] mip-access @yenshih 
- [x] mip-bridge-baidu #416  @yenshih 
- [x] mip-infinitescroll @yenshih 
- [x] mip-login-done @yenshih 
- [x] mip-share #465 @zoumiaojiang 
- [x] mip-accordion #433  @zoumiaojiang @clark-t 
- [x] mip-nav-slidedown @zoumiaojiang @clark-t 
- [x] mip-scrollbox #435 @zoumiaojiang @clark-t 
- [x] mip-ad #417   @zoumiaojiang 
- [x] mip-ad-ecom #440  @zoumiaojiang 
- [x] mip-analytics #422  @zoumiaojiang 
- [x] mip-stats-baidu #424 @zoumiaojiang 
- [x] mip-stats-cnzz #427  @zoumiaojiang 
- [x] mip-stats-tianrun #428  @zoumiaojiang 
- [x] mip-anim #454 @Brunoon 
- [x] mip-appdl #452 @Brunoon 
- [x] mip-gototop #450 @Brunoon 
- [x] mip-html-os #449   @Brunoon 
- [x] mip-link #448  @Brunoon 
- [x] mip-map #447  @Brunoon 
- [x] mip-sidebar #446  @Brunoon
- [x] mip-toggle #445  @Brunoon 
- [x] mip-app-banner #453  @Brunoon 
- [x] mip-group-selection #456  @Brunoon 
- [x] mip-audio #420  @huanghuiquan 
- [x] mip-semi-fixed #421  @huanghuiquan 
- [x] mip-experiment #442 @huanghuiquan 
- [x] mip-lightbox @huanghuiquan 
- [x] mip-custom @craigchencc 
- [x] mip-mustache @craigchencc 
- [x] mip-filter #443  @Ricardo-Li 
- [x] mip-form #460 @Ricardo-Li 
- [x] mip-history #444  @Ricardo-Li 
- [x] mip-install-serviceworker #432  @PengXing 
- [x] mip-showmore #429   @PengXing 
- [x] mip-list #423  @PengXing 
- [x] mip-vd-baidu #438   @chenqiushi 
- [x] mip-vd-tabs #457 @chenqiushi 
- [x] mip-widget-full-height #455 @chenqiushi 

共 39 个组件

> mip-story 由业务方 文杰 他们负责，不需要迁移
> mip-fixed & mip-bind 成内置组件了，不需要迁移
> mip-sample 应该是个样例组件，并且已没有使用量，不迁移

## 迁移注意事项

1. 转成 es6 语法, 在保证功能与 V1 一致的前提下可以适当改进代码逻辑
2. 需要保证文档提到的功能和例子的准确性
3. 领取组件后 at 自己的名字，并把组件位置移动到一起，组件领取尽量按分类划分

**Comment by PengXing** [comment]
分支为 `dev-sync`

**Comment by PengXing** [comment]
自测 checklist 放在这里，这里是汇总表，开发者自己负责的可以在下面进行评论

## 组件列表

- [ ] mip-access @yenshih 
- [ ] mip-bridge-baidu #416  @yenshih 
- [ ] mip-infinitescroll @yenshih 
- [ ] mip-login-done @yenshih 
- [ ] mip-share #465 @zoumiaojiang 
- [ ] mip-accordion #433  @zoumiaojiang 
- [ ] mip-nav-slidedown @zoumiaojiang 
- [ ] mip-scrollbox #435 @zoumiaojiang 
- [ ] mip-ad #417   @zoumiaojiang 
- [ ] mip-ad-ecom #440  @zoumiaojiang 
- [ ] mip-analytics #422  @zoumiaojiang 
- [ ] mip-stats-baidu #424 @zoumiaojiang 
- [ ] mip-stats-cnzz #427  @zoumiaojiang 
- [ ] mip-stats-tianrun #428  @zoumiaojiang 
- [ ] mip-anim #454 @Brunoon 
- [ ] mip-appdl #452 @Brunoon 
- [ ] mip-gototop #450 @Brunoon 
- [ ] mip-html-os #449   @Brunoon 
- [ ] mip-link #448  @Brunoon 
- [ ] mip-map #447  @Brunoon 
- [ ] mip-sidebar #446  @Brunoon
- [ ] mip-toggle #445  @Brunoon 
- [ ] mip-app-banner #453  @Brunoon 
- [ ] mip-group-selection #456  @Brunoon 
- [ ] mip-audio #420  @huanghuiquan 
- [ ] mip-semi-fixed #421  @huanghuiquan 
- [ ] mip-experiment #442 @huanghuiquan 
- [ ] mip-lightbox @huanghuiquan 
- [ ] mip-mustache @craigchencc 
- [ ] mip-filter #443  @Ricardo-Li 
- [ ] mip-form #460 @Ricardo-Li 
- [ ] mip-history #444  @Ricardo-Li 
- [ ] mip-install-serviceworker #432  @PengXing 
- [ ] mip-showmore #429   @PengXing 
- [ ] mip-list #423  @PengXing 
- [ ] mip-vd-baidu #438   @chenqiushi 
- [ ] mip-vd-tabs #457 @chenqiushi 
- [ ] mip-widget-full-height #455 @chenqiushi

**Comment by PengXing** [comment]
- [ ] mip-install-serviceworker #432  @PengXing 
  - [ ] iOS 10.3.2
  - [ ] iOS 12.1 
  - [ ] 小米 8(Android 9)
  - [ ] 红米 Note(Android 4.4)
  - [ ] Oppo(Android )
  - [ ] 三星(Android 8)
- [ ] mip-showmore #429   @PengXing 
- [ ] mip-list #423  @PengXing

**Comment by yenshih** [comment]
- [] mip-bridge-baidu
  - [ ] iOS 10.3.2
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] iOS 12.1 
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 小米 8(Android 9)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 红米 Note(Android 4.4)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] Oppo(Android 6.0.1)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 三星(Android 8)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
 - mip-infinitescroll
  - [ ] iOS 10.3.2
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] iOS 12.1 
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 小米 8(Android 9)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 红米 Note(Android 4.4)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] Oppo(Android 6.0.1)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 三星(Android 8)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器

**Comment by Ricardo-Li** [comment]
- [ ] mip-history #444 @Ricardo-Li 
  - [ ] iOS 10.3.2
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] iOS 12.1 
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 红米 Note(Android 4.4)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] Oppo(Android 6.0.1)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 三星(Android 8)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
- [ ] mip-filter #443  @Ricardo-Li 
  - [ ] iOS 10.3.2
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] iOS 12.1 
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 红米 Note(Android 4.4)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] Oppo(Android 6.0.1)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 三星(Android 8)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
- [ ] mip-form @Ricardo-Li 
  - [ ] iOS 10.3.2
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] iOS 12.1 
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 红米 Note(Android 4.4)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] Oppo(Android 6.0.1)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 三星(Android 8)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器

**Comment by craigchencc** [comment]
- [ ] mip-mustache
  - [x] iOS 10.3.2
    - [x] 百度
    - [x] Safari
    - [x] QQ 浏览器
    - [x] UC 浏览器
  - [ ] iOS 12.1 
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 小米 8(Android 9)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 红米 Note(Android 4.4)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] Oppo(Android 6.0.1)
    - [x] 百度
    - [x] 自带浏览器
    - [x] QQ 浏览器
    - [x] UC 浏览器
  - [ ] 三星(Android 8)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
- [ ] mip-infinitescroll
  - [x] iOS 10.3.2
    - [x] 百度
    - [x] Safari
    - [x] QQ 浏览器
    - [x] UC 浏览器
  - [ ] iOS 12.1 
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 小米 8(Android 9)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 红米 Note(Android 4.4)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] Oppo(Android 6.0.1)
    - [ ] 百度
    - [x] 自带浏览器
    - [x] QQ 浏览器
    - [x] UC 浏览器
  - [ ] 三星(Android 8)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器

**Comment by huanghuiquan** [comment]
- [ ] mip-experiment  @huanghuiquan 
  - [ ] iOS 12.0
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] iOS 11.3.1
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 小米 6 (Android 8.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 小米 5s Plus (Android 7.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 荣耀 H60 (Android 4.4.2)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 魅蓝 (Android 5.1)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器

- [ ] mip-audio  @huanghuiquan 
  - [ ] iOS 12.0
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] iOS 11.3.1
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 小米 6 (Android 8.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 小米 5s Plus (Android 7.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 荣耀 H60 (Android 4.4.2)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 魅蓝 (Android 5.1)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器

- [ ] mip-semi-fixed  @huanghuiquan 
  - [ ] iOS 12.0
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] iOS 11.3.1
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 小米 6 (Android 8.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 小米 5s Plus (Android 7.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 荣耀 H60 (Android 4.4.2)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 魅蓝 (Android 5.1)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器

**Comment by Brunoon** [comment]
- [ ] mip-anim #454 @Brunoon 
  - [ ] iOS 12.0
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] iOS 11.3.1
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 小米 6 (Android 8.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 小米 5s Plus (Android 7.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 荣耀 H60 (Android 4.4.2)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 魅蓝 (Android 5.1)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
- [ ] mip-appdl #452 @Brunoon 
  - [ ] iOS 12.0
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] iOS 11.3.1
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 小米 6 (Android 8.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 小米 5s Plus (Android 7.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 荣耀 H60 (Android 4.4.2)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 魅蓝 (Android 5.1)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
- [ ] mip-gototop #450 @Brunoon 
  - [ ] iOS 12.0
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] iOS 11.3.1
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 小米 6 (Android 8.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 小米 5s Plus (Android 7.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 荣耀 H60 (Android 4.4.2)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 魅蓝 (Android 5.1)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
- [ ] mip-html-os #449   @Brunoon 
  - [ ] iOS 12.0
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] iOS 11.3.1
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 小米 6 (Android 8.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 小米 5s Plus (Android 7.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 荣耀 H60 (Android 4.4.2)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 魅蓝 (Android 5.1)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
- [ ] mip-link #448  @Brunoon 
  - [ ] iOS 12.0
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] iOS 11.3.1
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 小米 6 (Android 8.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 小米 5s Plus (Android 7.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 荣耀 H60 (Android 4.4.2)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 魅蓝 (Android 5.1)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
- [ ] mip-map #447  @Brunoon 
  - [ ] iOS 12.0
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] iOS 11.3.1
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 小米 6 (Android 8.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 小米 5s Plus (Android 7.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 荣耀 H60 (Android 4.4.2)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 魅蓝 (Android 5.1)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
- [ ] mip-sidebar #446  @Brunoon
  - [ ] iOS 12.0
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] iOS 11.3.1
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 小米 6 (Android 8.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 小米 5s Plus (Android 7.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 荣耀 H60 (Android 4.4.2)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 魅蓝 (Android 5.1)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
- [ ] mip-toggle #445  @Brunoon 
  - [ ] iOS 12.0
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] iOS 11.3.1
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 小米 6 (Android 8.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 小米 5s Plus (Android 7.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 荣耀 H60 (Android 4.4.2)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 魅蓝 (Android 5.1)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
- [ ] mip-app-banner #453  @Brunoon 
  - [ ] iOS 12.0
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] iOS 11.3.1
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 小米 6 (Android 8.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 小米 5s Plus (Android 7.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 荣耀 H60 (Android 4.4.2)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 魅蓝 (Android 5.1)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
- [ ] mip-group-selection #456  @Brunoon 
  - [ ] iOS 12.0
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] iOS 11.3.1
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 小米 6 (Android 8.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 小米 5s Plus (Android 7.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 荣耀 H60 (Android 4.4.2)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 魅蓝 (Android 5.1)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器

**Comment by zoumiaojiang** [comment]
- [ ] mip-ad @zoumiaojiang  
  - [ ] iOS 12.0
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] iOS 10.3.2
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 红米 (Android 4.4.2)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] Meizu Pro 7 (Android 7.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 三星 S8 (Android 8.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
- [ ] mip-analytics @zoumiaojiang  
  - [ ] iOS 12.0
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] iOS 10.3.2
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 红米 (Android 4.4.2)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] Meizu Pro 7 (Android 7.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 三星 S8 (Android 8.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
- [ ] mip-ad-ecom @zoumiaojiang  
  - [ ] iOS 12.0
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] iOS 10.3.2
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 红米 (Android 4.4.2)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] Meizu Pro 7 (Android 7.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 三星 S8 (Android 8.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
- [ ] mip-stats-baidu @zoumiaojiang  
  - [ ] iOS 12.0
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] iOS 10.3.2
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 红米 (Android 4.4.2)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] Meizu Pro 7 (Android 7.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 三星 S8 (Android 8.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
- [ ] mip-stats-cnzz @zoumiaojiang  
  - [ ] iOS 12.0
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] iOS 10.3.2
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 红米 (Android 4.4.2)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] Meizu Pro 7 (Android 7.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 三星 S8 (Android 8.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
- [ ] mip-stats-tianrun @zoumiaojiang  
  - [ ] iOS 12.0
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] iOS 10.3.2
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 红米 (Android 4.4.2)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] Meizu Pro 7 (Android 7.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 三星 S8 (Android 8.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
- [ ] mip-share @zoumiaojiang  
  - [ ] iOS 12.0
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] iOS 10.3.2
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 红米 (Android 4.4.2)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] Meizu Pro 7 (Android 7.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 三星 S8 (Android 8.0)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器

**Comment by clark-t** [comment]
- [ ] mip-nav-slidedown @clark-t 
  - [ ] iOS 10.3.2
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] iOS 12.1 
    - [ ] 百度
    - [ ] Safari
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 小米 8(Android 9)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 红米 Note(Android 4.4)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] Oppo(Android 6.0.1)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器
  - [ ] 三星(Android 8)
    - [ ] 百度
    - [ ] 自带浏览器
    - [ ] QQ 浏览器
    - [ ] UC 浏览器

**Comment by PengXing** [comment]
项目已成功上线！可喜可贺
